### PR TITLE
Login-Logout

### PR DESCRIPTION
**Pull request by namneyugn21**
I change the navigation bar, and they look good now. 
Only problem that I am trying to fix is the Sign In and Sign Out Issue, this might be due to the controller thing. I can take a took later.

### CODE REVIEW

**Comment by kzcheng** [comment]
Nice!

Also I think if we have time, we can change the nav bar into a Thymeleaf component, then every page will be able to just reference and use it.

**Comment by kzcheng** [comment]
Noticed some weird minor bugs, let me see if I can document them.

**Comment by kzcheng** [comment]
Bug 1:

After logging in, the display shows the home page, but the URL is still on `/login`. It's probably better to make this a redirect to the actual homepage instead.

image

**Comment by kzcheng** [comment]
Bug 2:

After logging in, if you visit the actual homepage again, the "Sign In" button still won't get replaced by "Log Out".

image

**Comment by kzcheng** [comment]
Bug 3:

If you are already logged in, clicking the Sign In button again will redirect you to `/login`. But the behavior of displaying the testing "protected" page still exists.

image

**Review by kzcheng — CHANGES_REQUESTED** [review]
So yeah, there are still some behavior that might need some work on.

**Comment by kzcheng** [comment]
Do you want me to merge this pull request first, then begin a new branch to work on the fixes?

Or do you want to keep working on the same branch for now?

**Comment by namneyugn21** [comment]
I think it's better for you to merge this and I can work on the bugs

**Comment by kzcheng** [comment]
> I think it's better for you to merge this and I can work on the bugs

No problem! I'll merge this now.

Sorry for not seeing the reply earlier lol

Weird that I haven't received a notification for a new comment like this...

**Review by kzcheng — APPROVED** [review]

**Pull request merged**
